[tool.poetry]
name = "switcheroo"
version = "0.1.0"
description = ""
authors = ["Chris Withers <chris@withers.org>"]

[tool.poetry.dependencies]
python = "*"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
